### ISSUE TITLE
Translate readme to english

### ISSUE THREAD

**Issue by xaca** [xaca/ascii_menu#2]
Please help use, with readme translation. :ok_hand:

**Comment by saarques** [comment]
I would like to do it, can I take it? @xaca

**Comment by xaca** [comment]
@saarques Hello! yeah, please help us. :+1:

**Comment by saarques** [comment]
README.md has been translated in English #3 , please tell me if there is any problem! :)

**Comment by Curnal** [comment]
If anything else is needed, let us know!

**Comment by xaca** [comment]
@saarques Translation is great! thank you! We have more issues @Curnal take a look at [C:heart:ding Music](https://github.com/xaca/coding-music/issues/33)

**Comment by saarques** [comment]
It's my pleasure @xaca , Thank you!

**Comment by IRusio** [comment]
i think, that issue is ready to close

**Comment by xaca** [comment]
@IRusio Thank you. Yes, I'm closing now. We have more issues if you have time, take a look on [C:heart:ding music](https://github.com/xaca/coding-music/issues)

**Comment by xaca** [comment]
@IRusio Thank you. Yes, I'm closing now. We have more issues if you have time, take a look on [C:heart:ding music](https://github.com/xaca/coding-music/issues)
